"use strict";
const express = require("express");
const crypto = require("crypto");
const db = require("../db");
const config = require("../config");
const communication = require("../services/communication");
const { requireAuth, requireRole, requireTenant } = require("../middleware/auth");
const { effectiveTenantId } = require("../middleware/tenant");
const { asyncHandler, err, ok, toNum, cleanStr } = require("../util");
const router = express.Router();
const gateway = config.PAYMENT_GATEWAY;
function ref(){ return `BELLO-${Date.now()}-${crypto.randomBytes(4).toString("hex")}`; }
function secret(g){ return g === "paystack" ? config.PAYSTACK_SECRET_KEY : config.FLUTTERWAVE_SECRET_KEY; }
async function api(url, options){ const r=await fetch(url, options); const data=await r.json().catch(()=>({})); if(!r.ok||data.status===false) throw new Error(data.message||"Payment gateway request failed."); return data; }
async function mark(reference,status,providerData={}) {
 const p=await db.get("SELECT * FROM fee_payments WHERE transaction_number=? OR reference=?",[reference,reference]); if(!p)return null;
 if(p.status==="successful" && status!=="successful") return p;
 let receipt=p.receipt_number; if(status==="successful"&&!receipt) { receipt=`REC-${p.madrasa_id}-${String(p.id).padStart(6,"0")}`; await db.run("UPDATE fee_payments SET receipt_number=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND madrasa_id=?",[receipt,status,p.id,p.madrasa_id]); } else await db.run("UPDATE fee_payments SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND madrasa_id=?",[status,p.id,p.madrasa_id]);
 if(status==="successful"){ const s=await db.get("SELECT first_name,last_name FROM students WHERE id=? AND madrasa_id=?",[p.student_id,p.madrasa_id]); const users=await db.all("SELECT user_id FROM parent_links WHERE student_id=? AND madrasa_id=?",[p.student_id,p.madrasa_id]); await communication.createNotifications(p.madrasa_id,users.map(x=>x.user_id),{type:"payment_received",title:"Online payment successful",body:`Payment received for ${s?`${s.first_name} ${s.last_name}`:"student"}. Receipt ${receipt}.`,entity_type:"payment",entity_id:p.id}); }
 return Object.assign({},p,{status,receipt_number:receipt});
}
router.post("/initiate", requireAuth, requireTenant, requireRole("parent","madrasa_admin"), asyncHandler(async(req,res)=>{
 if(gateway==="none") return err(res,503,"Online payments are not configured. Please ask an administrator to configure a payment gateway.");
 const tid=effectiveTenantId(req); const b=req.body||{}; const studentId=toNum(b.student_id,0), feeId=toNum(b.fee_item_id,0), amount=Number(b.amount_ngn);
 if(!tid||!studentId||!feeId||!Number.isFinite(amount)||amount<=0) return err(res,400,"student_id, fee_item_id and a positive amount_ngn are required.");
 const student=await db.get("SELECT id,first_name,last_name,parent_phone,parent_name FROM students WHERE id=? AND madrasa_id=?",[studentId,tid]); const fee=await db.get("SELECT id,name_en FROM fee_items WHERE id=? AND madrasa_id=?",[feeId,tid]); if(!student||!fee)return err(res,404,"Student or fee item not found.");
 if(req.user.role==="parent" && !await db.get("SELECT id FROM parent_links WHERE user_id=? AND student_id=? AND madrasa_id=?",[req.user.id,studentId,tid])) return err(res,403,"You are not linked to this student.");
 const reference=ref(); const r=await db.run("INSERT INTO fee_payments (madrasa_id,student_id,fee_item_id,amount_ngn,payment_date,method,reference,transaction_number,recorded_by,status,notes,updated_at) VALUES (?,?,?,?,CURRENT_DATE,?,?,?,?,?,?,CURRENT_TIMESTAMP)",[tid,studentId,feeId,amount,gateway,reference,reference,req.user.id,"pending","gateway initiated"]);
 try { let data; if(gateway==="paystack") data=await api("https://api.paystack.co/transaction/initialize",{method:"POST",headers:{Authorization:`Bearer ${secret(gateway)}`,"Content-Type":"application/json"},body:JSON.stringify({email:req.user.email||`${req.user.username}@bello.local`,amount:Math.round(amount*100),reference,callback_url:config.PAYMENT_CALLBACK_URL,metadata:{madrasa_id:tid,student_id:studentId,fee_item_id:feeId}})}); else data=await api("https://api.flutterwave.com/v3/payments",{method:"POST",headers:{Authorization:`Bearer ${secret(gateway)}`,"Content-Type":"application/json"},body:JSON.stringify({tx_ref:reference,amount,currency:"NGN",redirect_url:config.PAYMENT_CALLBACK_URL,customer:{email:req.user.email||`${req.user.username}@bello.local`,name:student.parent_name||"Parent"},meta:{madrasa_id:tid,student_id:studentId,fee_item_id:feeId}})}); return ok(res,{payment_url:gateway==="paystack"?data.data.authorization_url:data.data.link,reference}); } catch(e){ await db.run("UPDATE fee_payments SET status='failed',updated_at=CURRENT_TIMESTAMP WHERE id=?",[r.lastInsertRowid]); throw e; }
}));
router.get("/callback", asyncHandler(async(req,res)=>{ const reference=cleanStr(req.query.reference||req.query.trx_ref,160); if(!reference)return res.status(400).send("Missing payment reference."); let status="failed"; try { if(gateway==="paystack"){const d=await api(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`,{headers:{Authorization:`Bearer ${secret(gateway)}`}}); status=d.data.status==="success"?"successful":"failed";} else { const d=await api(`https://api.flutterwave.com/v3/transactions/${encodeURIComponent(req.query.transaction_id||reference)}/verify`,{headers:{Authorization:`Bearer ${secret(gateway)}`}}); status=d.data&&d.data.status==="successful"?"successful":"failed";} const p=await mark(reference,status); return res.type("html").send(`<script>location.href='/#/portal/fees?payment=${encodeURIComponent(reference)}&status=${status}'</script>`); } catch(e){ await mark(reference,"failed"); return res.status(502).send("Payment verification failed. Please contact the school."); } }));
router.post("/webhook", asyncHandler(async(req,res)=>{ const sig=req.get("x-paystack-signature")||req.get("verif-hash")||""; const raw=JSON.stringify(req.body||{}); const expected=crypto.createHmac("sha512",secret(gateway)).update(raw).digest("hex"); if(!secret(gateway)||!sig||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return res.status(401).json({error:"Invalid webhook signature."}); const e=req.body||{}; const reference=e.data&& (e.data.reference||e.data.tx_ref); const event=e.event||e.type; if(reference&&/charge\.success|successful/i.test(event||e.data?.status))await mark(reference,"successful",e); else if(reference&&/charge\.failed|failed/i.test(event||e.data?.status))await mark(reference,"failed",e); res.json({received:true}); }));
router.get("/status/:reference", requireAuth, requireTenant, asyncHandler(async(req,res)=>{const tid=effectiveTenantId(req);const p=await db.get("SELECT id,status,receipt_number,reference,amount_ngn,student_id FROM fee_payments WHERE madrasa_id=? AND (reference=? OR transaction_number=?)",[tid,req.params.reference,req.params.reference]);if(!p)return res.status(404).json({error:"Payment not found."}); if(req.user.role === "parent" && !await db.get("SELECT id FROM parent_links WHERE madrasa_id=? AND user_id=? AND student_id=?",[tid,req.user.id,p.student_id])) return res.status(404).json({error:"Payment not found."}); ok(res,{payment:p});}));
module.exports=router;
