#!/bin/bash
# =============================================================================
# BELLO-INSTITUTE — isolated MySQL 8 TEST server
# -----------------------------------------------------------------------------
# Starts a dedicated, throwaway MySQL 8 instance for verification runs. It is
# NOT a production database: it listens on a non-default port, lives in its own
# data directory, and is created empty every time --fresh is passed.
#
# No credentials are stored in this file. The test password is taken from
# $TEST_MYSQL_PASSWORD (generated by the caller) and never echoed.
# =============================================================================
set -euo pipefail

MYSQL_HOME="${MYSQL_HOME:-/opt/mysql8}"
DATADIR="${MYSQL_TEST_DATADIR:-/opt/mysql-test/data}"
RUNDIR="${MYSQL_TEST_RUNDIR:-/opt/mysql-test/run}"
PORT="${TEST_MYSQL_PORT:-3307}"
SOCKET="$RUNDIR/mysql.sock"
LOG="$RUNDIR/mysqld.log"

mkdir -p "$RUNDIR"

if [ "${1:-}" = "--fresh" ]; then
  rm -rf "$DATADIR"
fi

if [ ! -d "$DATADIR/mysql" ]; then
  mkdir -p "$DATADIR"
  "$MYSQL_HOME/bin/mysqld" --no-defaults --initialize-insecure \
    --basedir="$MYSQL_HOME" --datadir="$DATADIR" --user="$(id -un)" \
    > "$RUNDIR/init.log" 2>&1
fi

exec "$MYSQL_HOME/bin/mysqld" --no-defaults \
  --basedir="$MYSQL_HOME" \
  --datadir="$DATADIR" \
  --port="$PORT" \
  --socket="$SOCKET" \
  --pid-file="$RUNDIR/mysqld.pid" \
  --log-error="$LOG" \
  --bind-address=127.0.0.1 \
  --max-connections="${TEST_MYSQL_MAX_CONNECTIONS:-300}" \
  --innodb-buffer-pool-size="${TEST_MYSQL_BUFFER_POOL:-512M}" \
  --innodb-flush-log-at-trx-commit=2 \
  --innodb-flush-method=fsync \
  --slow-query-log=ON \
  --slow-query-log-file="$RUNDIR/slow.log" \
  --long-query-time="${TEST_MYSQL_SLOW_SECONDS:-0.5}" \
  --log-output=FILE \
  --performance-schema=ON
